version: '3'

networks:
  internal:
    name: internal

services:
  api:
    container_name: todo.minimal.api
    image: vitormoschetta/todo.minimal.api
    build:
      context: .
      dockerfile: Dockerfile          
    ports:
      - 6001:6001
    networks:
      - internal
    depends_on:
      - db

  db:
    container_name: todo.minimal.api.postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: minimal
      POSTGRES_PASSWORD: Postgres@123
      POSTGRES_DB: todo-minimal-api-db
    ports:
      - 5432:5432
    expose:
      - 5432    
    networks:
      - internal